spring.application.name=AutoEscola3ESPH
server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/autoescola3esph?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:fiap}

api.security.token.secret=12345678